# Generated by Django 4.2.7 on 2023-11-16 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0016_revista2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetImagen',
            fields=[
                ('idLote', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('capitulo', models.CharField(max_length=50)),
                ('grupoImagen', models.ImageField(upload_to='D:\\Django Proyectos\\Gatsu\\static\\images')),
            ],
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.RemoveField(
            model_name='capitulo',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='capitulo',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='capitulo',
        ),
        migrations.RemoveField(
            model_name='mangagatsu',
            name='nombre_manga',
        ),
        migrations.RemoveField(
            model_name='nombremanga',
            name='revista',
        ),
        migrations.RemoveField(
            model_name='registropago',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Revista2',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='manga3',
            name='imagen',
            field=models.ImageField(upload_to='D:\\Django Proyectos\\Gatsu\\static\\images'),
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='MangaGatsu',
        ),
        migrations.DeleteModel(
            name='NombreManga',
        ),
        migrations.DeleteModel(
            name='RegistroPago',
        ),
        migrations.DeleteModel(
            name='Revista',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Valoracion',
        ),
        migrations.AddField(
            model_name='setimagen',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga3'),
        ),
    ]
